Italian basics Rules
doctrine/inflector pull request #197
Opened 2022-05-05 15:43 UTC by riettotek

I wrote the basics. I'm italian. 
I'm already using these rules for migrations. If u want to include them by reviewing . Thank u :)

2022-05-05 20:38 UTC, malarzm requested changes
Grazie mille per il lavoro iniziale @riettotek! 🇮🇹  

Apart from few comments I've left, the PR must meet our standards before merging:

1) pass all the checks (the coding style can be fixed by running `vendor/bin/phpcbf`)
2) have tests that prove your code is working as expected and preventing regressions in the future

2022-05-05 20:38 UTC, malarzm commented on lib/Doctrine/Inflector/Rules/Italian/Inflectible.php
> +        yield new Transformation(new Pattern('i$'), 'o');
This transformation will never happen given the previous one has exactly same catch pattern

2022-05-05 20:38 UTC, malarzm commented on lib/Doctrine/Inflector/Rules/Italian/Inflectible.php
> +        yield new Transformation(new Pattern('o$'), 'i');
These two rules could be merged into `new Pattern('i?o$')` I believe

2022-05-05 20:38 UTC, malarzm commented on lib/Doctrine/Inflector/Rules/Italian/Inflectible.php
> +       return yield new Substitution(new Word(''), new Word(''));
This looks unfinished

2022-05-05 20:38 UTC, malarzm commented on lib/Doctrine/Inflector/Rules/Italian/README.md
> +# doctrine-Italian-inflector-
This file seems irrelevant once we merge the PR

2022-05-05 20:38 UTC, malarzm commented on lib/Doctrine/Inflector/Rules/Italian/Uninflected.php
> +        yield new Pattern('.*ss');
These words looks like copy-pasted from English

2022-05-05 20:38 UTC, malarzm commented on lib/Doctrine/Inflector/Rules/Italian/Uninflected.php
> +        yield new Pattern('food');
Definitely

2025-06-30 08:07 UTC, f-liva commented
You can close this PR as the rules for Italian have already been included with my last PR.

2025-06-30 12:08 UTC, closed without merging