Add "is" to "are" irregular replacement
doctrine/inflector pull request #211
Opened 2022-10-25 14:39 UTC by mylesduncanking

For use in strings like "There **_is_** 1 staff member logged in" / "There **_are_** 2 staff members logged in".

Laravel blade example:
```
There {{ Str::plural('is', $count) }} {{ $count }} staff {{ Str::plural('member', $count) }} logged in
```

2022-10-25 15:05 UTC, derrabus requested changes
`$inflector->pluralize()` is not meant to conjugate verbs as far as I know. I don't think we should merge this change.

2022-10-25 19:25 UTC, malarzm commented
I agree with @derrabus, fi we start maintaining is/are next will be was/were, has/have, and eventually we'll end up with rules for normal verbs and their endings.

Inflector allows you to add your own rules to the ruleset: https://www.doctrine-project.org/projects/doctrine-inflector/en/2.0/index.html#custom-setup - I'd advise to add is/are as your custom rule in your project.

Thank you @mylesduncanking for proposition!

2022-10-25 19:25 UTC, closed without merging

2022-10-26 10:41 UTC, mylesduncanking commented
That makes sense, I wasn't aware of the custom rulesets which sounds like a good match for what I need at the moment.

Oversight on my part, I didn't check the other words to see it is just focused on nouns. It may be possible to expand to verbs fairly easily with some regex rules as there doesn't look to be many irregulars but that is for you to decide. I'm happy to propose another PR for this if you are interested.

[Singular-and-Plural-English-Verbs-Chart.pdf](https://assets.ltkcontent.com/files/Singular-and-Plural-English-Verbs-Chart.pdf)

Also, very minor, but as I was checking again to see that it is all nouns, "valve" is in the irregular list twice. Won't cause any issues I'm sure but thought I would mention it.

Thank you for the package though, very useful :)

2022-10-26 20:37 UTC, malarzm commented
> Oversight on my part, I didn't check the other words to see it is just focused on nouns.

No worries!

> It may be possible to expand to verbs fairly easily with some regex rules as there doesn't look to be many irregulars but that is for you to decide.

I'm mostly afraid for other languages :) For instance in Polish we'd have "jest/są" (is/are) but (sentences mean the same as your example):

- 1 osoba jest zalogowana - 1 => "jest", cool
- 2 osoby są zalogowane - 2 => "są", cool
- ...
- 5 osób jest zalogowanych - 5 => "jest", not right according to rules.

Of course we're not supporting Polish at the moment, I'm just using my mother tongue to prove a point ;) As much as your use case is clean and, frankly, tempting to use, I'm not sure it won't be a can of worms eventually.

> Also, very minor, but as I was checking again to see that it is all nouns, "valve" is in the irregular list twice. Won't cause any issues I'm sure but thought I would mention it.

Thanks, I'll remove it in a spare moment.

> Thank you for the package though, very useful :)

🍻